In [2]:
# Remove stopwords

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

example_sent = "This is a sample sentence, showing off the stop words filtration."
stop_words = set(stopwords.words('english'))

word_tokens = word_tokenize(example_sent.lower())
filtered_sentence = [w for w in word_tokens if not w in stop_words]
filtered_sentence = []

for w in word_tokens:
    if w not in stop_words:
        filtered_sentence.append(w)
 
print word_tokens
print filtered_sentence

['this', 'is', 'a', 'sample', 'sentence', ',', 'showing', 'off', 'the', 'stop', 'words', 'filtration', '.']
['sample', 'sentence', ',', 'showing', 'stop', 'words', 'filtration', '.']


In [8]:
# Sort the dictionay by value
import operator
x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
sorted_x = sorted(x.items(), key=operator.itemgetter(1))
print sorted_x


# Sort the dictionay by key
x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
sorted_x = sorted(x.items(), key=operator.itemgetter(0))
print sorted_x

# Sort the dictionay by value in descending
x = {1: 2, 3: 4, 4: 3, 2: 1, 0: 0}
sorted_x = sorted(x.items(), key=operator.itemgetter(1), reverse=True)
print sorted_x

[(0, 0), (2, 1), (1, 2), (4, 3), (3, 4)]
[(0, 0), (1, 2), (2, 1), (3, 4), (4, 3)]
<type 'list'>


In [3]:
# Remove punctuations

from nltk.tokenize import RegexpTokenizer
s = '''He said,"that's it." *u* Hello, World.'''
toker = RegexpTokenizer(r'((?<=[^\w\s])\w(?=[^\w\s])|(\W))+', gaps=True)
toker.tokenize(s)
['He', 'said', 'that', 's', 'it', 'Hello', 'World'] 

['He', 'said', 'that', 's', 'it', 'Hello', 'World']

In [ ]:
# Lemmatize

In [3]:
# Load Glove Embedding

import numpy as np

gloveFile = "glove.6B/glove.6B.50d.txt"

model = {}

with open(gloveFile, 'r') as f:
    for line in f:
        splitLine = line.split()
        word = splitLine[0]
        embedding = np.array([float(val) for val in splitLine[1:]])
        model[word] = embedding
    print "Done.",len(model)," words loaded!"    

Done. 400000  words loaded!


In [11]:
# Less frequent words are labeled as <unk>
print model['unk']

key = 'New Delhi'

if key in model:
    print model[key]
else:
    print model['unk']

[ -7.91490000e-01   8.66170000e-01   1.19980000e-01   9.22870000e-04
   2.77600000e-01  -4.91850000e-01   5.01950000e-01   6.07920000e-04
  -2.58450000e-01   1.78650000e-01   2.53500000e-01   7.65720000e-01
   5.06640000e-01   4.02500000e-01  -2.13880000e-03  -2.83970000e-01
  -5.03240000e-01   3.04490000e-01   5.17790000e-01   1.50900000e-02
  -3.50310000e-01  -1.12780000e+00   3.32530000e-01  -3.52500000e-01
   4.13260000e-02   1.08630000e+00   3.39100000e-02   3.35640000e-01
   4.97450000e-01  -7.01310000e-02  -1.21920000e+00  -4.85120000e-01
  -3.85120000e-02  -1.35540000e-01  -1.63800000e-01   5.23210000e-01
  -3.13180000e-01  -1.65500000e-01   1.19090000e-01  -1.51150000e-01
  -1.56210000e-01  -6.26550000e-01  -6.23360000e-01  -4.21500000e-01
   4.18730000e-01  -9.24720000e-01   1.10490000e+00  -2.99960000e-01
  -6.30030000e-03   3.95400000e-01]
[ -7.91490000e-01   8.66170000e-01   1.19980000e-01   9.22870000e-04
   2.77600000e-01  -4.91850000e-01   5.01950000e-01   6.07920000e-0

In [2]:
# Check if key is in dict
d = dict()
d["neelesh"] = 1

key = "neelesh"

if key in d:
    d[key] += 1
else:
    d[key] = 1

print d[key]

2


In [21]:
# add two array
word_embed = np.array
np.add(1.0, 4.0)
x1 = np.arange(9.0).reshape((3, 3))

x2 = np.arange(3.0)
x1 = np.add(x1, x2)
print x1

[[  0.   2.   4.]
 [  3.   5.   7.]
 [  6.   8.  10.]]


In [1]:
sent = "This IS MY LIFE"
words = sent.split()
print words[0].lower()

this


In [14]:
from numpy import dot
from numpy.linalg import norm

cosine_similarity = dot([-1, 0, -1], [1,0, 1])/(norm([-1, 0, -1]) * norm([1,0, 1]))

print cosine_similarity

-1.0


In [16]:
# Concatenate two arrays
import numpy as np

a = np.array([1, 2, 3, 4])
b = np.array([5, 6])
np.concatenate((a, b), axis=0)

array([1, 2, 3, 4, 5, 6])

In [17]:
tag = 'PER_Others'
print tag[:3]

PER
